language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

install:
  - yarn global add gatsby-cli

script:
  - yarn install
  - yarn build

addons:
  ssh_known_hosts: wiss.org

before_deploy:
- test $TRAVIS_TEST_RESULT = 0
- openssl aes-256-cbc -K $encrypted_2c430460807a_key -iv $encrypted_2c430460807a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avr --delete-after --quiet $TRAVIS_BUILD_DIR/public/ travis@wiss.org:$DEST_DIR
